{% set version = "1.8.157" %}

{% set posix = 'm2-' if win else '' %}

package:
  name: r-rockchalk
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rockchalk_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rockchalk/rockchalk_{{ version }}.tar.gz
  sha256: 814099ca8b1193992cd6e0af759a7d5bac74b891fbb4518c7f0e7fd56dcbe28d

build:
  number: 3
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]

  host:
    - r-base
    - r-mass
    - r-cardata
    - r-kutils
    - r-lme4

  run:
    - r-base
    - r-mass
    - r-cardata
    - r-kutils
    - r-lme4

test:
  commands:
    - $R -e "library('rockchalk')"           # [not win]
    - "\"%R%\" -e \"library('rockchalk')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=rockchalk
  license: GPL-3.0-or-later
  summary: A collection of functions for interpretation and presentation of regression analysis.  These functions are used to produce the statistics lectures in <http://pj.freefaculty.org/guides>. Includes regression diagnostics, regression tables, and plots of interactions and "moderator" variables. The emphasis is on "mean-centered"
    and "residual-centered" predictors. The vignette 'rockchalk' offers a fairly comprehensive overview.  The vignette 'Rstyle' has advice about coding in R.  The package title 'rockchalk' refers to our school motto, 'Rock Chalk Jayhawk, Go K.U.'.

  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - izahn
